import { EsfSlot } from "@/providers/CurrentFitProvider";

export const esiFlagToEsfSlot: Record<number, EsfSlot> = {
  11: { type: "Low", index: 1 },
  12: { type: "Low", index: 2 },
  13: { type: "Low", index: 3 },
  14: { type: "Low", index: 4 },
  15: { type: "Low", index: 5 },
  16: { type: "Low", index: 6 },
  17: { type: "Low", index: 7 },
  18: { type: "Low", index: 8 },
  19: { type: "Medium", index: 1 },
  20: { type: "Medium", index: 2 },
  21: { type: "Medium", index: 3 },
  22: { type: "Medium", index: 4 },
  23: { type: "Medium", index: 5 },
  24: { type: "Medium", index: 6 },
  25: { type: "Medium", index: 7 },
  26: { type: "Medium", index: 8 },
  27: { type: "High", index: 1 },
  28: { type: "High", index: 2 },
  29: { type: "High", index: 3 },
  30: { type: "High", index: 4 },
  31: { type: "High", index: 5 },
  32: { type: "High", index: 6 },
  33: { type: "High", index: 7 },
  34: { type: "High", index: 8 },
  92: { type: "Rig", index: 1 },
  93: { type: "Rig", index: 2 },
  94: { type: "Rig", index: 3 },
  125: { type: "SubSystem", index: 1 },
  126: { type: "SubSystem", index: 2 },
  127: { type: "SubSystem", index: 3 },
  128: { type: "SubSystem", index: 4 },
};
